RINGCENTRAL_SERVER: https://platform.devtest.ringcentral.com
RINGCENTRAL_CHATBOT_DATABASE_CONNECTION_URI:
RINGCENTRAL_CHATBOT_CLIENT_ID:
RINGCENTRAL_CHATBOT_CLIENT_SECRET:
RINGCENTRAL_CHATBOT_SERVER: https://<chatbot-server>
RINGCENTRAL_CHATBOT_ADMIN_USERNAME: admin
RINGCENTRAL_CHATBOT_ADMIN_PASSWORD: admin
